# Generated by Django 5.1.6 on 2025-03-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parkassist_slot_booking_transaction_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='PassWord',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='logintable',
            old_name='UserName',
            new_name='Username',
        ),
    ]
