# Generated by Django 5.1.6 on 2025-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_password_logintable_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='type',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingendtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingstarttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkassist',
            name='closingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkassist',
            name='openingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slotlocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
