# Generated by Django 5.1.6 on 2025-03-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_type_logintable_type_remove_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactiondate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
