# Generated by Django 5.1.6 on 2025-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slotlightstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
